spring.application.name=clase2-eventos
spring.datasource.url=jdbc:postgresql://localhost:5432/Homework2
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=KuTcJMcuTRvyILORnFNtCwoU1KNTKDWP0+wRCTo1Mdm/ap+j0+RXlBethAePbU1+IZtnvzBKFN2HZrcT879exQ==
jwt.expiration=86400000